const VAULT_CONFIG={popupPassword:"RED-FOX",defaultRevealCount:10,galleries:{
"OffxVauLt":{title:"Collection 001",revealCount:10,unlockCode:"OFFX-UNLOCK-001",media:[{type:"image",src:"gallery/OffxVauLt/01.jpg"},{type:"image",src:"gallery/OffxVauLt/02.jpg"},{type:"video",src:"gallery/OffxVauLt/03.mp4"}]},
"AccessBySomesh":{title:"Collection 002",revealCount:10,unlockCode:"ACCESS-UNLOCK-002",media:[{type:"image",src:"gallery/AccessBySomesh/01.jpg"},{type:"video",src:"gallery/AccessBySomesh/02.mp4"}]},
"HaCkeR-sOmesh":{title:"Collection 003",revealCount:10,unlockCode:"SOMESH-UNLOCK-003",media:[{type:"image",src:"gallery/HaCkeR-sOmesh/01.jpg"}]},
"OffxVauLt-001":{title:"Offx Collection",revealCount:10,unlockCode:"OFFX-UNLOCK-001",media:[]},
"AccessBySomesh-001":{title:"Somesh Collection",revealCount:10,unlockCode:"ACCESS-UNLOCK-002",media:[]},
"HaCkeR-sOmesh-001":{title:"Private Collection",revealCount:10,unlockCode:"SOMESH-UNLOCK-003",media:[]}}};
const $=id=>document.getElementById(id),screens=["intro","home","popup","loading","mediaLoading","locked","gallery","error","end"],show=id=>{screens.forEach(x=>$(x).classList.toggle("active",x===id));if(id!=="gallery")scrollTo(0,0)};
let current=null,visibleCount=0,index=0,touchX=0,timer=null,mediaTimer=null,galleryUnlocked=false;
setTimeout(()=>show("popup"),2600);
$("gateForm").addEventListener("submit",e=>{e.preventDefault();if($("gatePassword").value===VAULT_CONFIG.popupPassword){$("gateStatus").textContent="";$("gatePassword").value="";show("home")}else{$("gateStatus").textContent="Access Denied";$("gatePassword").select()}});
$("form").addEventListener("submit",e=>{e.preventDefault();const raw=$("code").value.trim(),key=Object.keys(VAULT_CONFIG.galleries).find(k=>k.toLowerCase()===raw.toLowerCase());if(!key||!VAULT_CONFIG.galleries[key].media.length){show("error");return}current=VAULT_CONFIG.galleries[key];visibleCount=0;galleryUnlocked=false;index=0;$("identity").value="";$("device").value="";$("code").value="";startVaultLoading()});
function startVaultLoading(){show("loading");const steps=[["Connecting to Vault...",12],["Verifying Code...",31],["Preparing Gallery...",55],["Loading Photos...",78],["Opening Vault...",100]];let s=0,p=0;clearInterval(timer);timer=setInterval(()=>{const [label,target]=steps[s];$("loadingText").textContent=label;p=Math.min(target,p+Math.max(1,Math.ceil((target-p)/4)));$("bar").style.width=p+"%";$("pct").textContent=p+"%";if(p>=target)s++;if(s>=steps.length){clearInterval(timer);setTimeout(startSequentialAccess,350)}},70)}
function startSequentialAccess(){$("galleryTitle").textContent=current.title;$("count").textContent="Photos & Videos • "+current.media.length;$("grid").innerHTML="";$("galleryState").textContent="";show("mediaLoading");loadMediaOneByOne()}
function loadMediaOneByOne(){if(!current||visibleCount>=current.media.length){show("gallery");return}if(!galleryUnlocked&&visibleCount>=Math.min(current.revealCount??VAULT_CONFIG.defaultRevealCount,current.media.length)){$("unlockCode").value="";$("unlockStatus").textContent="";show("locked");return}const media=current.media[visibleCount],position=visibleCount+1;$("mediaLoadingName").textContent=(media.type==="video"?"Video ":"Photo ")+position;$("mediaPosition").textContent=position+" / "+current.media.length;$("mediaPct").textContent="0%";$("mediaBar").style.width="0%";show("mediaLoading");const finish=()=>{clearInterval(mediaTimer);$("mediaPct").textContent="100%";$("mediaBar").style.width="100%";setTimeout(()=>{appendMedia(media,visibleCount);visibleCount++;loadMediaOneByOne()},220)};clearInterval(mediaTimer);let p=0;mediaTimer=setInterval(()=>{p=Math.min(92,p+Math.ceil((92-p)/3));$("mediaPct").textContent=p+"%";$("mediaBar").style.width=p+"%"},55);if(media.type==="video"){const probe=document.createElement("video");probe.preload="metadata";probe.onloadedmetadata=finish;probe.onerror=finish;probe.src=media.src}else{const probe=new Image();probe.onload=finish;probe.onerror=finish;probe.src=media.src}}
function appendMedia(m,i){const b=document.createElement("button");b.className="card media-card";b.type="button";if(m.type==="video"){const v=document.createElement("video");v.src=m.src;v.muted=true;v.preload="metadata";v.playsInline=true;b.append(v);const p=document.createElement("span");p.className="play";p.textContent="▶";b.append(p)}else{const img=document.createElement("img");img.src=m.src;img.loading="eager";img.alt="Gallery item "+(i+1);b.append(img)}b.onclick=()=>openViewer(i);$("grid").append(b)}
$("unlockForm").addEventListener("submit",e=>{e.preventDefault();if($("unlockCode").value.trim()===current.unlockCode){galleryUnlocked=true;$("unlockStatus").textContent="";loadMediaOneByOne()}else{$("unlockStatus").textContent="Access Denied";$("unlockCode").select()}});
function openViewer(i){index=i;updateViewer();$("viewer").classList.add("open");$("viewer").setAttribute("aria-hidden","false")}
function closeViewer(){$("viewer").classList.remove("open");$("viewer").setAttribute("aria-hidden","true");$("stage").innerHTML=""}
function updateViewer(){const m=current.media[index],stage=$("stage");stage.innerHTML="";if(m.type==="video"){const v=document.createElement("video");v.src=m.src;v.controls=true;v.autoplay=true;v.playsInline=true;v.preload="metadata";stage.append(v)}else{const img=document.createElement("img");img.src=m.src;img.alt="Gallery item "+(index+1);stage.append(img)}$("vcounter").textContent=(index+1)+" / "+current.media.length}
function downloadCurrent(){const m=current?.media[index];if(!m)return;const a=document.createElement("a");a.href=m.src;a.download=m.src.split("/").pop()||"offxvault-media";a.rel="noopener";document.body.appendChild(a);a.click();a.remove()}
function move(d){if(!current?.media.length)return;index=(index+d+current.media.length)%current.media.length;updateViewer()}
$("retry").onclick=()=>show("popup");$("back").onclick=()=>{current=null;show("home")};$("finish").onclick=()=>{current=null;show("end")};$("home").onclick=()=>show("home");$("close").onclick=closeViewer;$("download").onclick=downloadCurrent;$("prev").onclick=()=>move(-1);$("next").onclick=()=>move(1);$("viewer").addEventListener("click",e=>{if(e.target===$("viewer"))closeViewer()});document.addEventListener("keydown",e=>{if(!$("viewer").classList.contains("open"))return;if(e.key==="Escape")closeViewer();if(e.key==="ArrowLeft")move(-1);if(e.key==="ArrowRight")move(1)});$("viewer").addEventListener("touchstart",e=>touchX=e.changedTouches[0].clientX,{passive:true});$("viewer").addEventListener("touchend",e=>{const dx=e.changedTouches[0].clientX-touchX;if(Math.abs(dx)>45)move(dx<0?1:-1)},{passive:true});